version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
clone_depth: 1
init:
- cmd: >-
    SET PATH=C:\Applications\Atlassian\atlassian-plugin-sdk-6.3.6\bin;%JAVA_HOME%\bin;%PATH%;
    SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
    SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
install:
- ps: >-
    if (!(Test-Path -Path "C:\Applications\Atlassian\" )) {
      $url = "https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-windows"
      $output = "c:\atlassian-plugin-sdk-windows.exe"
      $start_time = Get-Date
      Import-Module BitsTransfer
      Start-BitsTransfer -Source $url -Destination $output
      $Process = [System.Diagnostics.Process]::Start("c:\atlassian-plugin-sdk-windows.exe", "-q")
      $Process.WaitForExit()
      if ($Process.ExitCode)
      {
        Write-Host "ended with an error"	
      }    else    {
        Write-Host "successful"
      }
    }

cache:
- C:\Applications\Atlassian
- C:\Applications\Atlassian\atlassian-plugin-sdk-6.3.6\repository

build_script:
- cmd: >-
    set MAVEN_HOME="C:\Applications\Atlassian\atlassian-plugin-sdk-6.3.6\apache-maven-3.2.1"
    set M2_HOME= "C:\Applications\Atlassian\atlassian-plugin-sdk-6.3.6\apache-maven-3.2.1"
    
    atlas-mvn clean package
artifacts:
- path: '\target\*.jar'
  name: app-delivery-management-bamboo-1.0-{branch}-{build}}
